language: python

install:
  - pip install -q --use-mirrors tox==2.1.1 coveralls==1.0a2

script:
  - coverage erase
  - tox
after_success:
  - coverage combine
  - coveralls

notifications:
  email:
    - goinnn@gmail.com